[package]
name = "mapgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib/main.rs"

[dependencies]
png = "0.17.6"
rgb = "0.8.33"
